use crate::{
    error::ZkvmError,
    instruction::{DecodedInstruction, IInstruction, Rv32Opcode},
    invariants,
    types::DecodeResult,
    util,
};

fn build_i(
    word: u32,
    opcode: Rv32Opcode,
    kind: IInstruction,
    rd: u8,
    rs1: u8,
    rs2: u8,
    imm: i32,
) -> DecodeResult<DecodedInstruction> {
    invariants::assert_decoded_registers(rd, rs1, rs2)?;

    Ok(DecodedInstruction::new_i(
        word,
        opcode,
        kind,
        rd,
        rs1,
        rs2,
        util::funct3(word),
        util::funct7(word),
        imm,
    ))
}

fn unsupported(word: u32) -> DecodeResult<DecodedInstruction> {
    Err(ZkvmError::UnsupportedInstruction {
        opcode: util::opcode(word),
        funct3: util::funct3(word),
        funct7: util::funct7(word),
    })
}

pub fn decode(word: u32) -> DecodeResult<DecodedInstruction> {
    let opcode = util::opcode(word);
    let funct3 = util::funct3(word);
    let funct7 = util::funct7(word);

    match opcode {
        0b0110111 => build_i(
            word,
            Rv32Opcode::Lui,
            IInstruction::Lui,
            util::rd(word),
            0,
            0,
            util::imm_u(word),
        ),
        0b0010111 => build_i(
            word,
            Rv32Opcode::Auipc,
            IInstruction::Auipc,
            util::rd(word),
            0,
            0,
            util::imm_u(word),
        ),
        0b1101111 => build_i(
            word,
            Rv32Opcode::Jal,
            IInstruction::Jal,
            util::rd(word),
            0,
            0,
            util::imm_j(word),
        ),
        0b1100111 => match funct3 {
            0b000 => build_i(
                word,
                Rv32Opcode::Jalr,
                IInstruction::Jalr,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            _ => unsupported(word),
        },
        0b1100011 => match funct3 {
            0b000 => build_i(
                word,
                Rv32Opcode::Branch,
                IInstruction::Beq,
                0,
                util::rs1(word),
                util::rs2(word),
                util::imm_b(word),
            ),
            0b001 => build_i(
                word,
                Rv32Opcode::Branch,
                IInstruction::Bne,
                0,
                util::rs1(word),
                util::rs2(word),
                util::imm_b(word),
            ),
            0b100 => build_i(
                word,
                Rv32Opcode::Branch,
                IInstruction::Blt,
                0,
                util::rs1(word),
                util::rs2(word),
                util::imm_b(word),
            ),
            0b101 => build_i(
                word,
                Rv32Opcode::Branch,
                IInstruction::Bge,
                0,
                util::rs1(word),
                util::rs2(word),
                util::imm_b(word),
            ),
            0b110 => build_i(
                word,
                Rv32Opcode::Branch,
                IInstruction::Bltu,
                0,
                util::rs1(word),
                util::rs2(word),
                util::imm_b(word),
            ),
            0b111 => build_i(
                word,
                Rv32Opcode::Branch,
                IInstruction::Bgeu,
                0,
                util::rs1(word),
                util::rs2(word),
                util::imm_b(word),
            ),
            _ => unsupported(word),
        },
        0b0000011 => match funct3 {
            0b000 => build_i(
                word,
                Rv32Opcode::Load,
                IInstruction::Lb,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            0b001 => build_i(
                word,
                Rv32Opcode::Load,
                IInstruction::Lh,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            0b010 => build_i(
                word,
                Rv32Opcode::Load,
                IInstruction::Lw,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            0b100 => build_i(
                word,
                Rv32Opcode::Load,
                IInstruction::Lbu,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            0b101 => build_i(
                word,
                Rv32Opcode::Load,
                IInstruction::Lhu,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            _ => unsupported(word),
        },
        0b0100011 => match funct3 {
            0b000 => build_i(
                word,
                Rv32Opcode::Store,
                IInstruction::Sb,
                0,
                util::rs1(word),
                util::rs2(word),
                util::imm_b(word),
            ),
            0b001 => build_i(
                word,
                Rv32Opcode::Store,
                IInstruction::Sh,
                0,
                util::rs1(word),
                util::rs2(word),
                util::imm_b(word),
            ),
            0b010 => build_i(
                word,
                Rv32Opcode::Store,
                IInstruction::Sw,
                0,
                util::rs1(word),
                util::rs2(word),
                util::imm_b(word),
            ),
            _ => unsupported(word),
        },
        0b0010011 => match funct3 {
            0b000 => build_i(
                word,
                Rv32Opcode::OpImm,
                IInstruction::Addi,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            0b010 => build_i(
                word,
                Rv32Opcode::OpImm,
                IInstruction::Slti,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            0b011 => build_i(
                word,
                Rv32Opcode::OpImm,
                IInstruction::Sltiu,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            0b100 => build_i(
                word,
                Rv32Opcode::OpImm,
                IInstruction::Xori,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            0b110 => build_i(
                word,
                Rv32Opcode::OpImm,
                IInstruction::Ori,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            0b111 => build_i(
                word,
                Rv32Opcode::OpImm,
                IInstruction::Andi,
                util::rd(word),
                util::rs1(word),
                0,
                util::imm_i(word),
            ),
            0b001 if funct7 == 0b0000000 => build_i(
                word,
                Rv32Opcode::OpImm,
                IInstruction::Slli,
                util::rd(word),
                util::rs1(word),
                0,
                util::shamt(word) as i32,
            ),
            0b101 if funct7 == 0b0000000 => build_i(
                word,
                Rv32Opcode::OpImm,
                IInstruction::Srli,
                util::rd(word),
                util::rs1(word),
                0,
                util::shamt(word) as i32,
            ),
            0b101 if funct7 == 0b0100000 => build_i(
                word,
                Rv32Opcode::OpImm,
                IInstruction::Srai,
                util::rd(word),
                util::rs1(word),
                0,
                util::shamt(word) as i32,
            ),
            _ => unsupported(word),
        },
        0b0110011 => match (funct3, funct7) {
            (0b000, 0b0000000) => build_i(
                word,
                Rv32Opcode::Op,
                IInstruction::Add,
                util::rd(word),
                util::rs1(word),
                util::rs2(word),
                0,
            ),
            (0b000, 0b0100000) => build_i(
                word,
                Rv32Opcode::Op,
                IInstruction::Sub,
                util::rd(word),
                util::rs1(word),
                util::rs2(word),
                0,
            ),
            (0b001, 0b0000000) => build_i(
                word,
                Rv32Opcode::Op,
                IInstruction::Sll,
                util::rd(word),
                util::rs1(word),
                util::rs2(word),
                0,
            ),
            (0b010, 0b0000000) => build_i(
                word,
                Rv32Opcode::Op,
                IInstruction::Slt,
                util::rd(word),
                util::rs1(word),
                util::rs2(word),
                0,
            ),
            (0b011, 0b0000000) => build_i(
                word,
                Rv32Opcode::Op,
                IInstruction::Sltu,
                util::rd(word),
                util::rs1(word),
                util::rs2(word),
                0,
            ),
            (0b100, 0b0000000) => build_i(
                word,
                Rv32Opcode::Op,
                IInstruction::Xor,
                util::rd(word),
                util::rs1(word),
                util::rs2(word),
                0,
            ),
            (0b101, 0b0000000) => build_i(
                word,
                Rv32Opcode::Op,
                IInstruction::Srl,
                util::rd(word),
                util::rs1(word),
                util::rs2(word),
                0,
            ),
            (0b101, 0b0100000) => build_i(
                word,
                Rv32Opcode::Op,
                IInstruction::Sra,
                util::rd(word),
                util::rs1(word),
                util::rs2(word),
                0,
            ),
            (0b110, 0b0000000) => build_i(
                word,
                Rv32Opcode::Op,
                IInstruction::Or,
                util::rd(word),
                util::rs1(word),
                util::rs2(word),
                0,
            ),
            (0b111, 0b0000000) => build_i(
                word,
                Rv32Opcode::Op,
                IInstruction::And,
                util::rd(word),
                util::rs1(word),
                util::rs2(word),
                0,
            ),
            _ => unsupported(word),
        },
        0b0001111 => match funct3 {
            0b000 => build_i(
                word,
                Rv32Opcode::MiscMem,
                IInstruction::Fence,
                0,
                0,
                0,
                util::imm_i(word),
            ),
            _ => unsupported(word),
        },
        0b1110011 => match word {
            0x0000_0073 => build_i(
                word,
                Rv32Opcode::System,
                IInstruction::Ecall,
                0,
                0,
                0,
                util::imm_i(word),
            ),
            0x0010_0073 => build_i(
                word,
                Rv32Opcode::System,
                IInstruction::Ebreak,
                0,
                0,
                0,
                util::imm_i(word),
            ),
            _ => unsupported(word),
        },
        _ => Err(ZkvmError::UnsupportedOpcode { opcode }),
    }
}
