pub type Reg = u8;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Instruction {
    Lui { rd: Reg, imm: i32 },
    Auipc { rd: Reg, imm: i32 },
    Jal { rd: Reg, imm: i32 },
    Jalr { rd: Reg, rs1: Reg, imm: i32 },

    Beq { rs1: Reg, rs2: Reg, imm: i32 },
    Bne { rs1: Reg, rs2: Reg, imm: i32 },
    Blt { rs1: Reg, rs2: Reg, imm: i32 },
    Bge { rs1: Reg, rs2: Reg, imm: i32 },
    Bltu { rs1: Reg, rs2: Reg, imm: i32 },
    Bgeu { rs1: Reg, rs2: Reg, imm: i32 },

    Lb { rd: Reg, rs1: Reg, imm: i32 },
    Lh { rd: Reg, rs1: Reg, imm: i32 },
    Lw { rd: Reg, rs1: Reg, imm: i32 },
    Lbu { rd: Reg, rs1: Reg, imm: i32 },
    Lhu { rd: Reg, rs1: Reg, imm: i32 },

    Sb { rs1: Reg, rs2: Reg, imm: i32 },
    Sh { rs1: Reg, rs2: Reg, imm: i32 },
    Sw { rs1: Reg, rs2: Reg, imm: i32 },

    Addi { rd: Reg, rs1: Reg, imm: i32 },
    Slti { rd: Reg, rs1: Reg, imm: i32 },
    Sltiu { rd: Reg, rs1: Reg, imm: i32 },
    Xori { rd: Reg, rs1: Reg, imm: i32 },
    Ori { rd: Reg, rs1: Reg, imm: i32 },
    Andi { rd: Reg, rs1: Reg, imm: i32 },
    Slli { rd: Reg, rs1: Reg, shamt: u8 },
    Srli { rd: Reg, rs1: Reg, shamt: u8 },
    Srai { rd: Reg, rs1: Reg, shamt: u8 },

    Add { rd: Reg, rs1: Reg, rs2: Reg },
    Sub { rd: Reg, rs1: Reg, rs2: Reg },
    Sll { rd: Reg, rs1: Reg, rs2: Reg },
    Slt { rd: Reg, rs1: Reg, rs2: Reg },
    Sltu { rd: Reg, rs1: Reg, rs2: Reg },
    Xor { rd: Reg, rs1: Reg, rs2: Reg },
    Srl { rd: Reg, rs1: Reg, rs2: Reg },
    Sra { rd: Reg, rs1: Reg, rs2: Reg },
    Or { rd: Reg, rs1: Reg, rs2: Reg },
    And { rd: Reg, rs1: Reg, rs2: Reg },

    Fence { pred: u8, succ: u8, fm: u8 },
    Ecall,
    Ebreak,

    Mul { rd: Reg, rs1: Reg, rs2: Reg },
    Mulh { rd: Reg, rs1: Reg, rs2: Reg },
    Mulhsu { rd: Reg, rs1: Reg, rs2: Reg },
    Mulhu { rd: Reg, rs1: Reg, rs2: Reg },
    Div { rd: Reg, rs1: Reg, rs2: Reg },
    Divu { rd: Reg, rs1: Reg, rs2: Reg },
    Rem { rd: Reg, rs1: Reg, rs2: Reg },
    Remu { rd: Reg, rs1: Reg, rs2: Reg },
}

impl Instruction {
    pub fn mnemonic(&self) -> &'static str {
        match self {
            Self::Lui { .. } => "lui",
            Self::Auipc { .. } => "auipc",
            Self::Jal { .. } => "jal",
            Self::Jalr { .. } => "jalr",
            Self::Beq { .. } => "beq",
            Self::Bne { .. } => "bne",
            Self::Blt { .. } => "blt",
            Self::Bge { .. } => "bge",
            Self::Bltu { .. } => "bltu",
            Self::Bgeu { .. } => "bgeu",
            Self::Lb { .. } => "lb",
            Self::Lh { .. } => "lh",
            Self::Lw { .. } => "lw",
            Self::Lbu { .. } => "lbu",
            Self::Lhu { .. } => "lhu",
            Self::Sb { .. } => "sb",
            Self::Sh { .. } => "sh",
            Self::Sw { .. } => "sw",
            Self::Addi { .. } => "addi",
            Self::Slti { .. } => "slti",
            Self::Sltiu { .. } => "sltiu",
            Self::Xori { .. } => "xori",
            Self::Ori { .. } => "ori",
            Self::Andi { .. } => "andi",
            Self::Slli { .. } => "slli",
            Self::Srli { .. } => "srli",
            Self::Srai { .. } => "srai",
            Self::Add { .. } => "add",
            Self::Sub { .. } => "sub",
            Self::Sll { .. } => "sll",
            Self::Slt { .. } => "slt",
            Self::Sltu { .. } => "sltu",
            Self::Xor { .. } => "xor",
            Self::Srl { .. } => "srl",
            Self::Sra { .. } => "sra",
            Self::Or { .. } => "or",
            Self::And { .. } => "and",
            Self::Fence { .. } => "fence",
            Self::Ecall => "ecall",
            Self::Ebreak => "ebreak",
            Self::Mul { .. } => "mul",
            Self::Mulh { .. } => "mulh",
            Self::Mulhsu { .. } => "mulhsu",
            Self::Mulhu { .. } => "mulhu",
            Self::Div { .. } => "div",
            Self::Divu { .. } => "divu",
            Self::Rem { .. } => "rem",
            Self::Remu { .. } => "remu",
        }
    }
}
