name: Lint
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy -- -D warnings
